apiVersion: apps/v1
kind: Deployment
metadata:
  name: bets
  labels:
    app: bets
spec:
  replicas: 1
  template:
    metadata:
      name: bets
      labels:
        app: bets
    spec:
      containers:
        - name: bets
          image: kurtis/bets:1.0.0-java-spring
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: bets
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
            - containerPort: 9091
              name: actuator
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: actuator
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: actuator
      restartPolicy: Always
  selector:
    matchLabels:
      app: bets
