apiVersion: v1
kind: Service
metadata:
  name: championships
  labels:
    app: championships
spec:
  selector:
    app: championships
  ports:
    - port: 8082
      name: http
      targetPort: http
  type: NodePort