apiVersion: v1
kind: Service
metadata:
  labels:
    app: bets
  name: bets
  namespace: demo
spec:
  clusterIPs:
    - 10.96.154.91
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      nodePort: 31979
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: bets
  type: NodePort
