// Package teams provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package teams

// Embedded defines model for Embedded.
type Embedded struct {
	Teams *[]Team `json:"teams,omitempty"`
}

// Link defines model for Link.
type Link struct {
	Href *string `json:"href,omitempty"`
}

// Links defines model for Links.
type Links struct {
	Championships *Link `json:"championships,omitempty"`
	Matches       *Link `json:"matches,omitempty"`
	Self          *Link `json:"self,omitempty"`
	Team          *Link `json:"team,omitempty"`
}

// Team defines model for Team.
type Team struct {
	Links    *Links  `json:"_links,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// Teams defines model for Teams.
type Teams struct {
	Embedded *Embedded   `json:"_embedded,omitempty"`
	Links    *TeamsLinks `json:"_links,omitempty"`
}

// TeamsLinks defines model for TeamsLinks.
type TeamsLinks struct {
	Self *Link `json:"self,omitempty"`
}
