apiVersion: apps/v1
kind: Deployment
metadata:
  name: matches
  labels:
    app: matches
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      name: matches
      labels:
        app: matches
        version: v1
    spec:
      containers:
        - name: matches
          image: kurtis/matches:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
          volumeMounts:
            - name: matches
              mountPath: /usr/src/data
      volumes:
        - name: matches
          configMap:
            name: matches
      restartPolicy: Always
  selector:
    matchLabels:
      app: matches
