apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: kurtis/bets
  newTag: 1.0.0-java-spring-otel-1.19.2
- name: kurtis/championships
  newTag: 1.0.0-java-spring-otel-1.19.2
- name: kurtis/matches
  newTag: 1.0.0-java-spring-otel-1.19.2
- name: kurtis/teams
  newTag: 1.0.0-java-spring-otel-1.19.2
patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: LOGGING_PATTERN_LEVEL
          value: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} %5p"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:opentelemetry-javaagent.jar -Dotel.javaagent.debug=true"
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_LOGS_EXPORTER
          value: none
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://collector.opentelemetry:4317
  target:
    kind: Deployment
    name: .*
    version: .*
