apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: kurtis/bets
  newTag: 1.0.0-java-spring-otel-1.19.2
- name: kurtis/championships
  newTag: 1.0.0-java-spring-otel-1.19.2
- name: kurtis/matches
  newTag: 1.0.0-java-spring-otel-1.19.2
- name: kurtis/teams
  newTag: 1.0.0-java-spring-otel-1.19.2
patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: LOGGING_PATTERN_LEVEL
          value: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} %5p"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:opentelemetry-javaagent.jar -Dotel.javaagent.debug=true"
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_LOGS_EXPORTER
          value: none
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://traces.opentelemetry:4317
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: http://metrics.opentelemetry:4317
        - name: OTEL_METRIC_EXPORT_INTERVAL
          value: "30000"
    - op: add
      path: /spec/replicas
      value: 3
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
          requests:
              cpu: 500m
              memory: 512Mi
          limits:
              memory: 512Mi
    - op: add
      path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
      value: 60
  target:
    kind: Deployment
    name: .*
    version: .*
