apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matches-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: matches
  endpoints:
    - port: metrics
      interval: 30s