apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: '[{"op":"add","path":"/spec/template/metadata/annotations","value":{"instrumentation.opentelemetry.io/inject-java":"true"}}]'
    target:
      kind: Deployment
