apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger
  namespace: jaeger
spec:
  ingressClassName: nginx
  rules:
    - host: jaeger.lvh.me
      http:
        paths:
          - backend:
              service:
                name: jaeger-query
                port:
                  name: http-query
            path: /
            pathType: ImplementationSpecific
